---
- name: install ntp
  apt:
    name:
      - ntp
    state: latest

- name: ntp config file
  notify: Restart NTP
  copy:
    src: "ntp.conf"
    dest: "/etc"
    owner: root
    group: adm
    mode: "0640"
