---
# Set true (e.g. in group_vars for your Raspberry Pi hosts/group) to enable
# eg. apt preference pinning
# Defaults to false so this role doesn't assume a particular inventory group
# layout.
std_packages_define_apt_preferences: false
std_packages_install_iperf3: false
std_packages_crond_log_processes: false
std_packages_timezone: "Europe/London"
