---
# tasks file for logrotate

- name: install logrotate
  apt:
    name:
      - logrotate
    state: latest

- name: compute effective logrotate_services (defaults + logrotate_services_override)
  set_fact:
    logrotate_services_effective: "{{ logrotate_services | combine(logrotate_services_override) }}"

- name: logrotate.d config files
  template:
    src: "{{ item.key }}.j2"
    dest: "/etc/logrotate.d/{{ item.key }}"
    owner: root
    group: adm
    mode: "0640"
    validate: "logrotate -d %s"
  loop: "{{ logrotate_services_effective | dict2items }}"
  when: item.value

- name: remove logrotate.d config files for disabled services
  file:
    path: "/etc/logrotate.d/{{ item.key }}"
    state: absent
  loop: "{{ logrotate_services_effective | dict2items }}"
  when: not item.value
