---
# tasks file for logrotate

- name: install logrotate
  apt:
    name:
      - logrotate
    state: latest

- name: logrotate.d config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logrotate.d/{{ item }}"
    owner: root
    group: adm
    mode: "0640"
  loop: "{{ logrotate_services }}"
