galaxy_info:
  author: Paul Blacknell
  description: Installs ntp and deploys a pool.ntp.org-based ntp.conf
  company: false

  issue_tracker_url: https://github.com/blacknell/ansible-roles/issues

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - debian
    - ntp
    - time

dependencies: []
