galaxy_info:
  author: Paul Blacknell
  description: Installs logrotate and deploys a fixed set of logrotate.d configs for common services

  issue_tracker_url: https://github.com/blacknell/ansible-roles/issues

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - debian
    - logging
    - logrotate

dependencies: []
