galaxy_info:
  author: Paul Blacknell
  description: Installs and keeps Syncthing up to date via Homebrew on macOS
  company: false

  issue_tracker_url: https://github.com/blacknell/ansible-roles/issues

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - syncthing
    - homebrew
    - macos

dependencies: []
