galaxy_info:
  author: Paul Blacknell
  description: Updates all apt packages to latest, dist-upgrades the OS, and cleans up unused packages/cache
  company: false

  issue_tracker_url: https://github.com/blacknell/ansible-roles/issues

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - debian
    - apt
    - updates
    - maintenance

dependencies: []
