---
- name: Ensure Syncthing is installed and up to date
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew:
    name: syncthing
    state: latest
    update_homebrew: true
  notify: Restart Syncthing service